# Generated by Django 5.0 on 2024-02-24 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donor_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('S_no', models.IntegerField(default=1)),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('address', models.TextField(max_length=100)),
                ('contact_number', models.BigIntegerField()),
                ('email', models.EmailField(max_length=50)),
                ('Blood_Group', models.CharField(max_length=10)),
                ('State', models.CharField(max_length=50)),
            ],
        ),
    ]
