# Generated by Django 5.0 on 2024-02-25 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0002_donor_data_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donor_data',
            name='Blood_Group',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='donor_data',
            name='S_no',
            field=models.IntegerField(),
        ),
    ]
