# Generated by Django 5.0 on 2024-02-26 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0003_alter_donor_data_blood_group_alter_donor_data_s_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('FeedBack_email', models.EmailField(max_length=50)),
                ('FeedBack', models.TextField()),
            ],
        ),
    ]
