# Generated by Django 5.0.3 on 2024-03-30 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0005_contact_details'),
    ]

    operations = [
        migrations.CreateModel(
            name='delete_data_req',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('SNo', models.IntegerField()),
                ('Delete_Name_req', models.CharField(max_length=30)),
                ('Delete_Contact_req', models.IntegerField(max_length=11)),
                ('Delete_EMAIL_req', models.EmailField(max_length=50)),
                ('Delete_city_req', models.IntegerField(max_length=20)),
                ('Delete_address_req', models.CharField(max_length=60)),
                ('Delete_Reason', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('D_Name', models.CharField(max_length=50)),
                ('D_email', models.EmailField(max_length=50)),
                ('D_Amount', models.IntegerField()),
                ('TransactionID', models.CharField(max_length=200)),
                ('paid', models.BooleanField(default='false')),
            ],
        ),
    ]
