# Generated by Django 5.0.3 on 2024-03-30 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bloodapp', '0007_alter_delete_data_req_delete_contact_req_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='delete_data_req',
            name='Delete_Contact_req',
            field=models.BigIntegerField(),
        ),
    ]
